### ISSUE TITLE
[MISSING FILE] supervisord.conf not found

### ISSUE THREAD

**Issue by dr3NRG** [helgeklein/samba-docker-home-server#1]
hi!
in "/dockerfile/init-fs.sh" file
exec /usr/bin/supervisord --nodaemon --configuration=/etc/supervisor/config/supervisord.conf
but that is not there and the smb fs not starting

**Comment by helgeklein** [comment]
Oops! The description of `supervisord.conf` (the supervisord config file) was missing from the [file server blog post](https://helgeklein.com/blog/samba-file-server-with-windows-acls-in-a-docker-container/). I just added the section **Supervisord Config File supervisord.conf**.
